# AppVeyor is used to build the editor and export templates for Windows.
#
# Download builds: https://bintray.com/calinou/godot/editor/_latestVersion#files
# GitHub repository: https://github.com/Calinou/godot-builds
#
# This build script is licensed under CC0 1.0 Universal:
# https://creativecommons.org/publicdomain/zero/1.0/

image: Visual Studio 2017
shallow_clone: true

environment:
  SCONS_OPTIONS: progress=no

  matrix:
    - TARGET: editor
    - TARGET: templates

install:
  - pip install --egg scons # `--egg` is required for use with AppVeyor
  - git clone --depth=1 https://github.com/godotengine/godot.git
  - cd godot\

build_script:
  - if %TARGET%==editor call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsDevCmd.bat" -arch=x64
  - if %TARGET%==editor scons platform=windows tools=yes target=release_debug %SCONS_OPTIONS%
  - if %TARGET%==editor call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsDevCmd.bat" -arch=x86
  - if %TARGET%==editor scons platform=windows tools=yes target=release_debug %SCONS_OPTIONS%
  - if %TARGET%==templates call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsDevCmd.bat" -arch=x64
  - if %TARGET%==templates scons platform=windows tools=no target=release %SCONS_OPTIONS%
  - if %TARGET%==templates call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsDevCmd.bat" -arch=x86
  - if %TARGET%==templates scons platform=windows tools=no target=release %SCONS_OPTIONS%

# Only release export templates are built for now, pretend that release-mode binaries are
# debug-mode templates to avoid errors in the editor's export dialog
after_build:
  - set BUILD_DATE=
  - for /f "delims=" %a in ('..\appveyor\get_date.cmd') do @set BUILD_DATE=%a
  - set BUILD_VERSION=
  - for /f "delims=" %a in ('git rev-parse --short=7 HEAD') do @set BUILD_VERSION=%a
  - set BUILD_ID=%BUILD_DATE%.%BUILD_VERSION%

  - if %TARGET%==editor mkdir %BUILD_ID%
  - if %TARGET%==editor 7z a %BUILD_ID%\Godot-Windows-x86_64-%BUILD_ID%.zip %APPVEYOR_BUILD_FOLDER%\godot\bin\godot.windows.opt.tools.64.exe
  - if %TARGET%==editor 7z a %BUILD_ID%\Godot-Windows-x86-%BUILD_ID%.zip %APPVEYOR_BUILD_FOLDER%\godot\bin\godot.windows.opt.tools.32.exe
  - if %TARGET%==editor git clone --depth=1 https://github.com/Calinou/godot.msi
  - if %TARGET%==editor cd godot.msi\
  - if %TARGET%==editor copy /Y ..\platform\windows\godot.ico godot.ico
  - if %TARGET%==editor copy /Y ..\bin\godot.windows.opt.tools.64.exe godot.exe
  - if %TARGET%==editor call "%WIX%\bin\candle.exe" godot.wxs -dexe_path=godot.exe -dversion=3.0.0.0
  - if %TARGET%==editor call "%WIX%\bin\light.exe" godot.wixobj
  - if %TARGET%==editor move godot.msi ..\%BUILD_ID%\Godot-Windows-x86_64-%BUILD_ID%.msi
  - if %TARGET%==editor copy /Y ..\bin\godot.windows.opt.tools.32.exe godot.exe
  - if %TARGET%==editor call "%WIX%\bin\candle.exe" godot.wxs -dexe_path=godot.exe -dversion=3.0.0.0
  - if %TARGET%==editor call "%WIX%\bin\light.exe" godot.wixobj
  - if %TARGET%==editor move godot.msi ..\%BUILD_ID%\Godot-Windows-x86-%BUILD_ID%.msi

  - if %TARGET%==templates mkdir bin\templates\
  - if %TARGET%==templates echo "3.0-alpha" > bin\templates\version.txt
  - if %TARGET%==templates copy bin\godot.windows.opt.64.exe bin\templates\windows_64_debug.exe
  - if %TARGET%==templates copy bin\godot.windows.opt.32.exe bin\templates\windows_32_debug.exe
  - if %TARGET%==templates copy bin\godot.windows.opt.64.exe bin\templates\windows_64_release.exe
  - if %TARGET%==templates copy bin\godot.windows.opt.32.exe bin\templates\windows_32_release.exe
  - if %TARGET%==templates cd bin\
  - if %TARGET%==templates 7z a -r Godot-Templates-Windows-%BUILD_ID%.zip templates\
  - if %TARGET%==templates move Godot-Templates-Windows-%BUILD_ID%.zip Godot-Templates-Windows-%BUILD_ID%.tpz

artifacts:
  - path: '**\*.zip'
  - path: '**\*.msi'
  - path: '**\*.tpz'

deploy:
  - provider: BinTray
    username: calinou
    api_key:
      secure: GJf+DF+dDdNyHsFP01JqBDaVUTI6jQ7VtDrDVp1S7vD94kT8/AbSOZSxIXyb7MBr
    subject: calinou
    repo: godot
    package: editor
    publish: true
    override: true
